import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title className="title">Welcome to my portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {/* <div className="animateme">
          <ul className="bgBubbles">
            <li>Mobile</li>
            <li>Web</li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
          </ul>
        </div> */}
        <div className="x1">.</div>
        <div className="x2">
          &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.
        </div>
        <div className="x3">.</div>
        <div className="x5"></div>
        <h1 className={styles.title}>
          <text x="2">
            {/* <textPath xlink:href="#curve"> */}
            Welcome
            {/* </textPath> */}
          </text>

          <div id="canvasContainer">to my portfolio</div>

          <svg>
            <defs>
              <filter id="flyOn">
                <feTurbulence
                  id="turbulence"
                  baseFrequency="0.02"
                  numOctaves="5"
                  result="noise"
                  seed="3"
                />
                <feDisplacementMap in="SourceGraphic" in2="noise" scale="15" />
              </filter>
            </defs>
          </svg>
        </h1>
        {/* </h1> */}
      </main>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
